= Cyface Android Publish

This is a https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins[convention plugin] implemented as https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins[precompiled script plugin].

This Gradle Plugin is currently only tested with Gradle 7 and 8.


[[license]]
== License
Copyright 2021-2023 Cyface GmbH

This file is part of the Cyface Publish Plugin for Android.

The Cyface Publish Plugin for Android is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The Cyface Publish Plugin for Android is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with the Cyface Publish Plugin for Android. If not, see http://www.gnu.org/licenses/.
